# Generated by Django 5.0.2 on 2024-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='static/images'),
        ),
    ]
