# Generated by Django 5.0.2 on 2024-03-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0003_product_company_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='projectStore/static/images'),
        ),
    ]
