# Generated by Django 5.0.2 on 2024-03-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0006_customer_order_deliveryaddress_ordereditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transction_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
