# Generated by Django 5.0.2 on 2024-03-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0007_order_transction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='customerInfo',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customerInfo',
            new_name='customer',
        ),
    ]
