# Generated by Django 5.0.2 on 2024-03-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0008_rename_customerinfo_deliveryaddress_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedItems',
            new_name='OrderedItem',
        ),
    ]
