# Generated by Django 5.0.2 on 2024-03-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0009_rename_ordereditems_ordereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offerprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
