# Generated by Django 5.0.2 on 2024-03-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0010_product_offerprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='quantityOfItems',
            new_name='quantity',
        ),
    ]
