# Generated by Django 5.0.2 on 2024-04-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0013_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='homePageProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(default=0, upload_to='images/projectStore/static/images/sportsDress')),
                ('price', models.FloatField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('digitalItems', models.BooleanField(null=True)),
                ('offerprice', models.IntegerField(blank=True, null=True)),
                ('fewleft', models.CharField(blank=True, max_length=50, null=True)),
                ('hotDeal', models.CharField(blank=True, max_length=50, null=True)),
                ('freeDelivery', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recomnded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(default=0, upload_to='images/recommenedItems')),
                ('price', models.FloatField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('digitalItems', models.BooleanField(null=True)),
                ('offerprice', models.IntegerField(blank=True, null=True)),
                ('fewleft', models.CharField(blank=True, max_length=50, null=True)),
                ('hotDeal', models.CharField(blank=True, max_length=50, null=True)),
                ('freeDelivery', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
