# Generated by Django 5.0.2 on 2024-04-03 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectStore', '0014_homepageproducts_recomnded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homePageProducts',
        ),
        migrations.DeleteModel(
            name='recomnded',
        ),
    ]
